CREATE TABLE [Recenze] (
	[id] INTEGER NOT NULL IDENTITY,
	[id_knihy] INTEGER NOT NULL,
	[id_recenzenta] INTEGER NOT NULL,
	[datum] DATE NOT NULL,
	[hodnoceni] INTEGER NOT NULL CHECK([hodnoceni] BETWEEN 1 AND 10),
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Autori] (
	[id] INTEGER NOT NULL IDENTITY,
	[jmeno] NVARCHAR(255) NOT NULL,
	[prijmeni] NVARCHAR(255) NOT NULL,
	[datum_narozeni] DATE NOT NULL,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [Knihy] (
	[id] INTEGER NOT NULL IDENTITY,
	[nazev] NVARCHAR(200) NOT NULL,
	[rokVydani] INTEGER NOT NULL,
	[zanr] NVARCHAR(50) NOT NULL,
	PRIMARY KEY([id])
);
GO

CREATE TABLE [KnihaAutori] (
	[id_knihy] INTEGER NOT NULL,
	[id_autora] INTEGER NOT NULL,
	PRIMARY KEY([id_knihy], [id_autora])
);
GO

CREATE TABLE [Recenzenti] (
	[id] INTEGER NOT NULL IDENTITY,
	[uzivatelske_jmeno] NVARCHAR(100) NOT NULL UNIQUE,
	[email] NVARCHAR(255) NOT NULL UNIQUE,
	[datum_registrace] DATE NOT NULL,
	PRIMARY KEY([id])
);
GO


ALTER TABLE [KnihaAutori]
ADD FOREIGN KEY([id_knihy])
REFERENCES [Knihy]([id])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [KnihaAutori]
ADD FOREIGN KEY([id_autora])
REFERENCES [Autori]([id])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [Recenze]
ADD FOREIGN KEY([id_knihy])
REFERENCES [Knihy]([id])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO
ALTER TABLE [Recenze]
ADD FOREIGN KEY([id_recenzenta])
REFERENCES [Recenzenti]([id])
ON UPDATE NO ACTION ON DELETE CASCADE;
GO